name: GHCR Retention Policy

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  clean-ghcr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Prune old images
        uses: snok/container-retention-policy@3b0972b2276b171b212f8c4efbca59ebba26eceb # v3.0.1
        with:
          account: ${{ github.repository_owner }}
          image-names: ${{ github.event.repository.name }}
          cut-off: 2 months ago UTC
          keep-at-least: 10
          account-type: personal
          token: ${{ secrets.GITHUB_TOKEN }}
